import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          RelajaciN(),
        ]),
      ),
    );
  }
}

class RelajaciN extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 440,
          height: 956,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFF14749A)),
          child: Stack(
            children: [
              Positioned(
                left: 145,
                top: 620,
                child: Text(
                  'Respira....',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 36,
                    fontFamily: 'ABeeZee',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 123,
                top: 694,
                child: Container(
                  width: 194,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF2EC8B9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 165,
                top: 707,
                child: SizedBox(
                  width: 118,
                  height: 25,
                  child: Text(
                    '¡Estoy mejor!',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 17,
                      fontFamily: 'Istok Web',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 376,
                top: 88,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 255,
                  children: [
                    Container(
                      width: 18,
                      height: 18,
                      decoration: ShapeDecoration(
                        color: const Color(0xFFF04CFF),
                        shape: OvalBorder(),
                      ),
                    ),
                    Container(
                      width: 18,
                      height: 18,
                      decoration: ShapeDecoration(
                        color: const Color(0xFFF04CFF),
                        shape: OvalBorder(),
                      ),
                    ),
                    Container(
                      width: 18,
                      height: 18,
                      decoration: ShapeDecoration(
                        color: const Color(0xFFFFF400),
                        shape: OvalBorder(),
                      ),
                    ),
                    Container(
                      width: 48,
                      height: 48,
                      decoration: ShapeDecoration(
                        shape: OvalBorder(
                          side: BorderSide(
                            width: 1,
                            color: const Color(0xFFBCE973),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 28,
                top: 98,
                child: Container(
                  width: 48,
                  height: 43,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: const Color(0x00FBFBFB)),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 32,
                top: 198,
                child: Container(
                  width: 383,
                  height: 378,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/383x378"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 163,
                top: 64,
                child: Text(
                  'iBreath',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 36,
                    fontFamily: 'ADLaM Display',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}